//16 Base colors
#define black   0  
#define white   42 
#define red     3  
#define lime    12 
#define blue    48 
#define yellow  15 
#define cyan    60 
#define magenta 51 
#define grey    43 
#define maroon  2  
#define olive   10 
#define green   8  
#define purple  34 
#define teal    40 
#define navy    32 
#define orange  7
#define dark_grey  37