
//VOICES BANK 1
#define GRAND_PIANO_1 1
#define BRIGHT_PIANO_2 2
#define EL_GRAND_PIANO 3
#define HONKY_TONK_PIANO 4
#define EL_PIANO_1 5
#define EL_PIANO_2 6
#define HARPSICHORD 7
#define CLAVI 8
#define CELESTA 9
#define GLOCKENSPIEL 10
#define MUSIC_BOX 11
#define VIBRAPHONE 12
#define MARIMBA 13
#define XYLOPHONE 14
#define TUBULAR_BELLS 15
#define SANTUR 16
#define DRAWBAR_ORGAN 17
#define PERCUSSIVE_ORGAN 18
#define ROCK_ORGAN 19
#define CHURCH_ORGAN 20
#define REED_ORGAN 21
#define ACCORDION_FRENCH 22
#define HARMONICA 23
#define TANGO_ACCORDION 24
#define AC_GUITAR_NYLON 25
#define AC_GUITAR_STEEL 26
#define EL_GUITAR_JAZZ 27
#define EL_GUITAR_CLEAN 28
#define EL_GUITAR_MUTED 29
#define OVERDRIVEN_GUITAR 30
#define DISTORTION_GUITAR 31
#define GUITAR_HARMONICS 32
#define GUN_SHOT 128











//DRUM SETS
#define STANDARD_SET   1
#define POWER_SET      17
#define BRUSH_SET      41
#define ORCHESTRA_SET  49
#define CM_SET         128
